stadium = input("경기장이 어디입니까?")
winner = input("이긴팀은 어디입니까?")
loser = input("진팀은 어디입니까? ")
best_player = input("우수선수는 누구입니까? ")
score = input("스코어는 몇대몇입니까? ")
print("")
print("===========================================")
print("오늘 %s에서 야구경기가 열렸습니다." %stadium)
print("%s 와 %s 은 치열한 공방전을 펼쳤습니다." %(winner,loser))
print("%s 이 맹활약을 하였습니다." %best_player)
print("결국 %s 가 %s 를 %s로 이겼습니다." %(winner,loser,score))
print("===========================================")
print("")
